Thunder over nh
FRC-1721/1721-InfiniteRecharge pull request #48
Opened 2021-08-27 19:31 UTC by KhanSimeoni

2021-08-29 20:13 UTC, KenwoodFox commented on src/main/java/frc/robot/RobotContainer.java
> +    //intake.setDefaultCommand(new PurgeIntake(intake));  // Uncomment this if you want the intake to default purge
Default purging may not be something we actually want in comp, can we discuss this sometime?

2021-08-29 20:21 UTC, jazzyjazz654321 commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    double dampenedSteerage = 0.4 * Math.pow(steerage, 3);
wahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh:D

2021-08-29 20:55 UTC, KenwoodFox commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    double dampenedSteerage = 0.4 * Math.pow(steerage, 3);
> wahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh:D

Yeah lol, he is baby.

2021-08-30 19:25 UTC, KenwoodFox commented on src/main/java/frc/robot/Constants.java
> +    public static final int Intake_Deploy = 5; // Configured never
Make sure to modify the `Configured never` comment when assigning these sorts of things, helps us judge on the fly how old a change is without using `git blame`

Not a big deal though

2021-09-08 21:42 UTC, KenwoodFox requested changes
Line too long, wayyyy too long XD

2021-09-08 21:42 UTC, KenwoodFox commented on src/main/java/frc/robot/RobotContainer.java
> +    //    () -> OperatorStick.getRawAxis(Constants.OperatorInputSettings.Purge_Axis))); //TODO: This gets in the way of the preivious intake deafult, so purge does not work. Possible fix: converge bo
This line is too long <3

2021-09-13 00:39 UTC, KenwoodFox commented
Everybody did amazing thank you!

2021-09-13 00:40 UTC, merged